services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PGURL: "postgres://postgres:postgres@db:5432/produtos"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: produtos
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - backend
    environment:
      FLASK_APP: "app"
      FLASK_ENV: "development"
      API_URL: "http://backend:8000/api/v1/produtos/"